### PR TITLE
Modern profile support

### PR DESCRIPTION
**Pull request by NattyNarwhal**
It slurps modern Chrome/V8 CPU profiles now. The format changed from hierarchical to just a flat array and referencing based on IDs, and moving the metadata into a call frame object, so things have been slightly tweaked around that. Tested with trivial examples; may need more work since it's just a trivial adaptation.

Screenshot from 2021-01-29 14-42-46

### CODE REVIEW

**Comment by jlfwong** [comment]
Hi @NattyNarwhal

I never use this library any more, since I do all my analysis in [speedscope](https://github.com/jlfwong/speedscope) nowadays. I am, in fact, working on callgrind import into speedscope: https://github.com/jlfwong/speedscope/issues/18

I'm unlikely to want to invest any more time into this repository. Would you be interested in having commit access and publish access to the npm package?

**Comment by NattyNarwhal** [comment]
Yeah, it was pretty easy to determine you were working on speedscope. It was useful for me to fix this library anyways, so I'd be OK with taking maintenance of this from you.

**Comment by jlfwong** [comment]
Invited you as a collaborator on GitHub. If you give me your npm handle, I'll invite you there too.

My only ask for you as maintainer is to not give access to anyone else who hasn't contributed real, useful code to the repository. There's been a history of npm packages being used to inject malicious code, and would rather not be part of that unfortunate lineage :)

**Comment by NattyNarwhal** [comment]
It's [~calvinb](https://www.npmjs.com/~calvinb) (Just had to make it today since I haven't done npm package maintenance before.).

And yeah, I'm quite familar with the abuse of new shady maintainers.

**Comment by jlfwong** [comment]
Okay, invited! Let me know if you have any questions. Feel free to merge this PR as you see fit

**Comment by NattyNarwhal** [comment]
Sorry for not getting back to you sooner; stuff came up here. I don't seem to have merge permissions, am I missing something?

**Comment by NattyNarwhal** [comment]
Haha, I'm a doofus and forgot the invitation was sitting in my inbox, thinking I had accepted it already. I'm merging now.

**Pull request merged**
